### ISSUE TITLE
GAZ license

### ISSUE THREAD

**Issue by cmungall** [EnvironmentOntology/gaz#18]
Looks like in this repo and in the OBO metadata GAZ is asserted to be CC-BY:

https://github.com/OBOFoundry/OBOFoundry.github.io/commit/27de0327bac9e00a7ef9e1d63cacb93d8d2878d8#diff-55585add55c612de501c3934421cb36c
(wasn't part of a PR or issue)

I think this requires further discussion

**Comment by cmungall** [comment]
My own vote would be for CC-0. If this cannot be done then I would like to see a CC-0 subset that can be loaded into Wikidata

**Comment by pbuttigieg** [comment]
+1 for CC-0

**Comment by lschriml** [comment]
Yes, that is the license I chose for GAZ.

Lynn

**Comment by lschriml** [comment]
When I was asked to put up the repo, this was part of the task. The license aligns with the other OBO projects.

If GAZ gets added to Wikidata it could be CC0.

I’ve not seen a ticket regarding GAZ being added to Wikidata.

What is the plan ?
Who is working on it, and who will be responsible for coordinating ongoing work with Wikidata once GAZ is added ?

Are there other projects in the works for GAZ ?

Lynn

**Comment by pbuttigieg** [comment]
@lschriml : I think we should make the move to CC-0 here and in ENVO regardless of the relationship to Wikidata. The nature of ontology content makes CC-BY impractical (e.g. attributing IRIs? To whom? With what technical overhead? )

The discussion on linking with Wikidata should be developed in a separate issue, perhaps #3. If we have solid documentation, the Wikidata user/editor community itself can maintain the link and be a great source of potential coeditors for GAZ branches.

**Comment by pbuttigieg** [comment]
Xref https://github.com/OBOFoundry/OBOFoundry.github.io/issues/285 https://github.com/EnvironmentOntology/envo/issues/600

**Comment by lschriml** [comment]
I’m fine with CC0

I’ll make the change.

Agreed:
Let’s get the Wikidata work documented in a separate ticket.

Cheers,
Lynn

**Comment by lschriml** [comment]
license updated in OBO Foundry:  
 url: https://creativecommons.org/publicdomain/zero/1.0/
  label: CC0 1.0 Universal
